apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: juice-shop
  namespace: juice-shop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: juice-shop
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50