# HTTPS - Main application
server {
    listen 80 default_server;
    server_name _;

    include snippets/proxy-headers.conf;

    location / {
        proxy_pass http://127.0.0.1:8081;
        include snippets/proxy-headers.conf;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8000;
        include snippets/proxy-headers.conf;
    }

    location /images/ {
        proxy_pass http://127.0.0.1:8000/images;
        include snippets/proxy-headers.conf;
    }

    location /recommendations/ {
        proxy_pass http://127.0.0.1:8001;
        include snippets/proxy-headers.conf;
    }

    location /inventory/ {
        proxy_pass http://127.0.0.1:8002;
        include snippets/proxy-headers.conf;
    }

    location /checkout/ {
        proxy_pass http://127.0.0.1:8003;
        include snippets/proxy-headers.conf;
    }
}