---
- name: AS3
  hosts: bigip
  connection: httpapi
  gather_facts: false

  # Connection Info
  vars:
    ansible_host: 
    ansible_user: 
    ansible_httpapi_password: 
    ansible_httpapi_port: 8443
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    # List of partitions/tenants to manage
    as3_tenants:
      #- "demo_app"
      #- "juice_shop_app"
      #- "dvwa_app"
      #- "dvga_app"
      #- "Shared"
      #- "Demo_Application"


  tasks:

    - name: Deploy or Update AS3
      f5networks.f5_bigip.bigip_as3_deploy:
          content: "{{ lookup('file', 'combined-as3.json') }}"
      tags: [ deploy ]

    - name: Delete AS3 Deployment
      f5networks.f5_bigip.bigip_as3_deploy:
        tenant: "{{ as3_tenant_name }}"
        state: absent
      tags: [ never, delete ]

    - name: Delete Mulitple AS3 deployments
      f5networks.f5_bigip.bigip_as3_deploy:
        tenant: "{{ item }}"
        state: absent
      loop: "{{ as3_tenants }}"
      tags: [ never, delete-all ]